version: "3"
networks:
  neo4j:
    external: false
services:
  neo4j:
    image: neo4j:3.4.18-enterprise
    container_name: neo4j
    environment:
      - TZ=Asia/Shanghai
      - NEO4J_AUTH=neo4j/123456
      - NEO4J_dbms_memory_heap_max__size=512M
      - NEO4J_dbms_db_auth_enabled=false
      - NEO4J_dbms_security_timezone=SYSTEM
      - NEO4J_db_temporal_timezone=Asia/Shanghai
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ${MIDDLEWARE_BASE_VOLUME}/neo4j/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped
    networks:
      - neo4j
