
#user  nobody;
#user root;
worker_processes 2;


#pid        logs/nginx.pid;
events {
    worker_connections 1024;
}

stream {
    #云平台
    upstream cloud {
        server 172.21.150.185;
    }
    # 网关服务
    upstream fsu_gateway {
        server 172.21.150.185:8080;
    }
    server {
        listen 80,443;
        proxy_pass cloud;
    }
    server {
        listen 8080;
        proxy_pass fsu_gateway;
    }
}

http {
    include mime.types;
    default_type application/octet-stream;
    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';
    #access_log  logs/access.log  main;
    sendfile on;
    #tcp_nopush     on;
    #keepalive_timeout  0;
    keepalive_timeout 65;
    #gzip  on;


    server {
        listen 80;
        client_max_body_size 20m;
        proxy_buffer_size 128k;
        proxy_buffers 32 128k;
        proxy_busy_buffers_size 128k;

        #控制中心
        location ^~ /proxy_controller_center/ {
            proxy_pass http://controller_center_web/;
            proxy_set_header Host $http_host;
        }
        #安消监控系统
        location ^~ /proxy_iot_firesafety/ {
            proxy_pass http://firesafety_server/;
            proxy_set_header Host $http_host;
        }
        #自动化中台
        location ^~ /proxy_automate_middleground/ {
            proxy_pass http://automate_middleground/;
            proxy_set_header Host $host;
        }
		#消防环境监控系统
        location ^~ /proxy_power_env/ {
            proxy_pass http://power_env_server/;
            proxy_set_header Host $http_host;
        }
        #神经元系统
        location ^~ /proxy_neure/ {
            proxy_pass http://neure_server/;
            proxy_set_header Host $http_host;
        }

		#资产服务
        #location ^~ /proxy_assets/ {
        #    proxy_pass http://assets_server/;
        #    proxy_set_header Host $http_host;
        #}
		#资产服务
        location ^~ /proxy_assetsSress/ {
            proxy_pass http://assets_server/;
            proxy_set_header Host $http_host;
        }
        #ap服务的页面资源转发
        location ^~ /page_route_privilege/ {
            proxy_pass http://ap_server/;
            proxy_set_header Host $http_host;
        }
        #ap后台的服务请求转发
        location ^~ /proxy_ap/ {
            proxy_pass http://ap_server/;
            proxy_set_header Host $http_host;
        }
        # 查看nginx的并发连接数配置
        location /NginxStatus
        {
             stub_status             on;
             access_log              off;
             auth_basic              "NginxStatus";
        }
        #ip/host 直接跳转至index.html使用
        rewrite ^/index$ http://$server_addr/index.html permanent;
        #rewrite "^/$" /index.html permanent;
        rewrite ^/$ http://$http_host/index.html permanent;
        #rewrite ^/$ /index.html permanent;
        rewrite "^/res/index.html$" http://$server_addr/index.html permanent;
        #默认请求ap服务
        #		location ^(.*)$ {
        #
        #			rewrite ^(.*)$ /index.html last;
        #		}

        location ^~ / {
           # proxy_pass http://ap_server/;
            proxy_pass http://controller_center_web/;
            proxy_set_header Host $http_host;
        }

        #error_page  404              /404.html;
        # redirect server error pages to the static page /50x.html
        #
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root html;
        }
    }
    #	include minifsu.conf;
    include conf.d/*.conf;

}
