version: '3.1'

networks:
  zookeeper_net:
    external: false #会自动创建网卡
services:
  zoo1:
    image: zookeeper:3.4.14
    restart: unless-stopped
    hostname: zoo1
    ports:
      - 2181:2181
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.zookeeper == zoo1]
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/middleware/zookeeper/data:/data
      - /home/middleware/zookeeper/datalog:/datalog
    logging:
      driver: "json-file"
      options:
        max-zise: "500m"
        max-file: "3"
    networks:
      - zookeeper_net
      

  zoo2:
    image: zookeeper:3.4.14
    restart: unless-stopped
    hostname: zoo2
    ports:
      - 2182:2181
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.zookeeper == zoo2]
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/middleware/zookeeper/data:/data
      - /home/middleware/zookeeper/datalog:/datalog
    logging:
      driver: "json-file"
      options:
        max-zise: "500m"
        max-file: "3"
    networks:
      - zookeeper_net
      

  zoo3:
    image: zookeeper:3.4.14
    restart: unless-stopped
    hostname: zoo3
    ports:
      - 2183:2181
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.zookeeper == zoo3]
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/middleware/zookeeper/data:/data
      - /home/middleware/zookeeper/datalog:/datalog
    logging:
      driver: "json-file"
      options:
        max-zise: "500m"
        max-file: "3"
    networks:
      - zookeeper_net
