version: "3"
networks:
  zookeeper:
    external: false
services:
  zookeeper:
    image: zookeeper:3.4.14
    container_name: zookeeper
    environment:
      - JVMFLAGS=-Xmx256m
    ports:
      - "2181:2181"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    networks:
      - zookeeper