#!/bin/sh

vpn_user=$1
vpn_password=$2

if [ -z ${vpn_user} ] || [ -z ${vpn_password} ]; then
	echo "Usage: $0 user password"
	exit 1
fi

vpn_deluser ${vpn_user}

cat >> /home/xl2tp/chap-secrets <<EOF
"${vpn_user}" "*" "${vpn_password}" "*"
EOF

cat >> /home/xl2tp/chap-secretss <<EOF
${vpn_user} : EAP "${vpn_password}"
${vpn_user} : XAUTH "${vpn_password}"
EOF