version: "3"
networks:
  nginx:
    external: false
services:
  nginx:
    image: nginx:1.21.6-perl
    container_name: nginx
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${MIDDLEWARE_BASE_VOLUME}/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ${MIDDLEWARE_BASE_VOLUME}/nginx/conf/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    # network_mode: host #nginx网络配置需与宿主机一致，方便nginx配置文件默认域名为127.0.0.1 #考虑hostname统一配置解决此问题
    networks:
      - nginx
    extra_hosts:
      - singleton.tech:${HOST_IP} #配置主机ip