version: "3"
networks:
  portainer:
    external: false
services:
  registry:
    image: portainer/portainer-ce:2.15.1
    container_name: registry
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "19000:9000"
    restart: unless-stopped
    networks:
      - portainer