version: '3.7'


networks:
  kafka_net:
    external: false

services:

  kafka1:
    image: 'bitnami/kafka:2.8.1'
    restart: unless-stopped
    #container_name: kafka1
    ports:
      - "9093:9092"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.kafka == kafka_group1]
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_ADVERTISED_HOST_NAME: dev-centos-234                ## 修改:宿主机IP
      KAFKA_CFG_ADVERTISED_PORT: 9093                                 ## 修改:宿主机映射port
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.234:9093    ## 绑定发布订阅的端口。修改:宿主机IP
      KAFKA_CFG_ZOOKEEPER_CONNECT: "192.168.0.234:2181,192.168.0.234:2182,192.168.0.234:2183"
      KAFKA_CFG_NUM_PARTITIONS: 6
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
#      KAFKA_CFG_LOG_RETENTION_BYTES: 1271088640 #单个topic保存128M缓存
      KAFKA_CFG_LOG_RETENTION_HOURS: 1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "./kafka/kafka1/docker.sock:/var/run/docker.sock"
      - "./kafka/kafka1/data/:/bitnami/kafka/data"
    networks:
      - kafka_net


  kafka2:
    image: 'bitnami/kafka:2.8.1'
    restart: unless-stopped
    #container_name: kafka2
    ports:
      - "9094:9092"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.kafka == kafka_group1]
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_BROKER_ID: 2
      KAFKA_CFG_ADVERTISED_HOST_NAME: dev-centos-234                ## 修改:宿主机IP
      KAFKA_CFG_ADVERTISED_PORT: 9094                               ## 修改:宿主机映射port
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.234:9094   ## 修改:宿主机IP
      KAFKA_CFG_ZOOKEEPER_CONNECT: "192.168.0.234:2181,192.168.0.234:2182,192.168.0.234:2183"
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_NUM_PARTITIONS: 6
 #     KAFKA_CFG_LOG_RETENTION_BYTES: 1271088640 #单个topic保存128M缓存
      KAFKA_CFG_LOG_RETENTION_HOURS: 1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "./kafka/kafka2/docker.sock:/var/run/docker.sock"
      - "./kafka/kafka2/data/:/bitnami/kafka/data"
    networks:
      - kafka_net

  kafka3:
    image: 'bitnami/kafka:2.8.1'
    restart: unless-stopped
    #container_name: kafka3
    ports:
      - "9095:9092"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.kafka == kafka_group1]
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_BROKER_ID: 3
      KAFKA_CFG_ADVERTISED_HOST_NAME: dev-centos-234             ## 修改:宿主机IP
      KAFKA_CFG_ADVERTISED_PORT: 9095                              ## 修改:宿主机映射port
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.234:9095   ## 修改:宿主机IP
      KAFKA_CFG_ZOOKEEPER_CONNECT: "192.168.0.234:2181,192.168.0.234:2182,192.168.0.234:2183"
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_NUM_PARTITIONS: 6
  #    KAFKA_CFG_LOG_RETENTION_BYTES: 1271088640 #单个topic保存128M缓存
      KAFKA_CFG_LOG_RETENTION_HOURS: 1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "./kafka/kafka3/docker.sock:/var/run/docker.sock"
      - "./kafka/kafka3/data/:/bitnami/kafka/data"
    networks:
      - kafka_net

  kafka-manager:
    #image: sheepkiller/kafka-manager:latest
    image: zenko/kafka-manager:latest
    restart: unless-stopped
    #container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.kafka == kafka_group1]
    links:            # 连接本compose文件创建的container
      - kafka1
      - kafka2
      - kafka3

    environment:
      ZK_HOSTS: 192.168.0.234:2181,192.168.0.234:2182,192.168.0.234:2183
      TZ: CST-8
    networks:
      - kafka_net
