version: "3.6"
networks:
  zentao-net:
    external: false
services:
  neo4j:
    image: easysoft/zentao:12.3.3
    container_name: zentao
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
      - IS_CONTAINER=true
      # - MYSQL_HOST=127.0.0.1
      # - MYSQL_PORT=3306
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=root
      # - MYSQL_DB=zentao
      - DEBUG=1
    volumes:
      - ${MIDDLEWARE_BASE_VOLUME}/zentao/mysqldata:/var/lib/mysql
      - ${MIDDLEWARE_BASE_VOLUME}/zentao/zentaopms:/www/zentaopms
      - ${MIDDLEWARE_BASE_VOLUME}/zentao/temp:/app/zentaopms/temp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8001:80
    restart: unless-stopped
    networks:
      - zentao-net