version: "3"
networks:
  redis:
    external: false
services:
  redis:
    image: redis:6.2.6
    container_name: redis
    command: /usr/local/etc/redis/redis.conf #如果配置本地配置文件则该配置需要生效
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${MIDDLEWARE_BASE_VOLUME}/redis/data:/data
      - ${MIDDLEWARE_BASE_VOLUME}/redis/conf:/usr/local/etc/redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - redis